apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: score-service
  namespace: gamehub
  labels:
    release: prometheus
    app: score-service
spec:
  selector:
    matchLabels:
      app: score-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - gamehub
